services:
  # Banco de Dados Relacional Principal
  postgres:
    image: postgres:15
    container_name: distrischool-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: distrischool_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Banco de Dados NoSQL (Opcional, listado na arquitetura para microsserviços específicos)
  mongodb:
    image: mongo:6
    container_name: distrischool-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Zookeeper (Necessário para gerenciar o Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: distrischool-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: distrischool-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_HOST
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data:
  mongodb_data: